
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: moveHalfway_int
// VERSION: 0002
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Move Time Slider to the nearest integering number frame inbetween the next and previous keyframes.
// 
// ------------------------------------------------------------------- 
//
// RUN COMMAND:
// MoveHalfway_Int() ;
// ------------------------------------------------------------------- 
// CHANGELOG:
// 0002: If no objects are selected, script will jump to midpoint of playback range.
// 
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc MoveHalfway_Int() {
    
    // create string from selected
    string $sel[] = `ls -sl` ;
    
    if(size($sel) == 0) {
        // define timeslider range
        int $startTime = `playbackOptions -q -min` ;
        int $endTime = `playbackOptions -q -max` ;
        
        // get midpoint of range
        int $midTime = ($startTime + $endTime)/2 ;
        currentTime $midTime ;   
    }
    
    else {
        
        // initialize keyframes
        int $prevKeyframe = `findKeyframe -timeSlider -which previous` ;  
        int $nextKeyframe = `findKeyframe -timeSlider -which next` ;
        
        // get midpoint
        int $midPoint = ($nextKeyframe + $prevKeyframe)/2 ;
        currentTime $midPoint ;   
    }
}