
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: moveHalfway_float
// VERSION: 0002
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Move Time Slider to the nearest floating number frame inbetween the next and previous keyframes.
// 
// ------------------------------------------------------------------- 
//
// RUN COMMAND:
// MoveHalfway_Float ;
// ------------------------------------------------------------------- 
// CHANGELOG:
// 0002: If no objects are selected, script will jump to midpoint of playback range.
//  
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc MoveHalfway_Float() {
    
    // create string from selected
    string $sel[] = `ls -sl` ;
    
    if(size($sel) == 0) {
        // define timeslider range
        float $startTime = `playbackOptions -q -min` ;
        float $endTime = `playbackOptions -q -max` ;
        
        // get midpoint of range
        float $midTime = ($startTime + $endTime)/2 ;
        currentTime $midTime ;   
    }
    
    else {

        // initialize keyframes
        float $prevKeyframe = `findKeyframe -timeSlider -which previous` ;  
        float $nextKeyframe = `findKeyframe -timeSlider -which next` ;
        
        // get midpoint
        float $midPoint = ($nextKeyframe + $prevKeyframe)/2 ;
        currentTime $midPoint ;   
    }   
}