/* 
// ------------------------------------------------------------------------------ //
// SCRIPT: mr_create_sphereAtCursor.mel
// VERSION: 0001
//
// CREATORS: Maria Robertson
// ---------------------------------------
//
// DESCRIPTION: 
// Create a sphere wherever the mouse cursor is hovering over.
//
// ---------------------------------------
// RUN COMMANDS:
// ---------------------------------------

mr_create_sphereAtCursor() ;

// ------------------------------------------------------------------------------ //
*/

global proc mr_create_sphereAtCursor() {
    
    $sphere = `polySphere -r 1 -sx 20 -sy 20 -ax 0 1 0 -cuv 2 -ch 1` ;
    
    
    float $pos[] = `autoPlace -um` ;
    move $pos[0] $pos[1] $pos[2] $sphere ;
    
}