
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: findConstraintTargets
// VERSION: 0001
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Select any targets that the selected object is constraining.
// 
// -------------------------------------------------------------------
//
// RUN COMMAND:
// FindConstraintTargets() ;
//
// -------------------------------------------------------------------
// RESEARCH THAT HELPED:
// How to find driver of selected object - https://forums.cgsociety.org/t/how-to-query-a-connectionsOfSelected-target-list-without-knowing-the-constraint-type/1309588/2
//
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc FindConstraintTargets() {

    // declare all constraint connections on selected
    string $connections[] = `listConnections -type "constraint"` ;
    // remove duplicate listings
    $connections = stringArrayRemoveDuplicates($connections) ;
        
    string $targets[] ;
    
    // find the parent of each connection
    $targets = `listRelatives -p $connections` ;
    // remove duplicate listings
    $targets = stringArrayRemoveDuplicates($targets) ;
    
    if (size($targets) == 0 ) {
        print "No targets found. \n" ;
    }
    else {
        select $targets ;
    }
}



 