
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: moveHalfway_int
// VERSION: 0001
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Move Time Slider to the nearest integering number frame inbetween the next and previous keyframes.
// 
// ------------------------------------------------------------------- 
//
// RUN COMMAND:
// MoveHalfway_Int() ;
//
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc MoveHalfway_Int() {
    
    // initialize keyframes
    int $prevKeyframe = `findKeyframe -timeSlider -which previous` ;  
    int $nextKeyframe = `findKeyframe -timeSlider -which next` ;
    
    // get midpoint
    int $midPoint = ($nextKeyframe + $prevKeyframe)/2 ;
    currentTime $midPoint ;   
}