
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: mr_select_currentFrameKeysOfSelected 
// VERSION: 0001
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Select all keys of selected objects that are on the current frame.
// 
// ---------------------------------------
// RUN COMMANDS:
// ---------------------------------------
/*

mr_select_currentFrameKeysOfSelected() ;

*/
//
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc mr_select_currentFrameKeysOfSelected() {

    // Create an array from selected
    string $sel[] = `ls -sl` ;
    
    // create array of visible curves in Graph Editor
    // -cs flag means curves shown here
    string $visibleAnimCurvesInGraphEd[] = `animCurveEditor -q -cs graphEditor1GraphEd` ;
    
	// get current time
    float $currentTime = `currentTime -q` ;
    // deselect all keys
    selectKey -clear ;   
		
    //For each object selected
    for ($i=0; $i < `size $sel`; $i++) {  
		// add any keys at the current time to key selection
        selectKey -add  -t ($currentTime) ;
    }    
}