
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: zeroSelectedKeysInGraphEditor 
// VERSION: 0001
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Zero the values of any keys selected in the Graph Editor.
// 
// ------------------------------------------------------------------- 
//
// RUN COMMAND:
// ZeroSelectedKeysInGraphEditor() ;
//
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc ZeroSelectedKeysInGraphEditor() {

    keyframe -an keys -vc 0 ;
	
}