
// ------------------------------------------------------------------------------------------------------------------------------------------------
// SCRIPT: zeroSelectedChannelBoxAttr 
// VERSION: 0001
//
// CREATORS: Maria Robertson
// -------------------------------------------------------------------
//
// DESCRIPTION: 
// Zero out the values of selected attributes in the Channel Box.
// 
// ------------------------------------------------------------------- 
//
// RUN COMMAND:
// ZeroSelectedChannelBoxAttr() ;
//
// ------------------------------------------------------------------------------------------------------------------------------------------------

global proc ZeroSelectedChannelBoxAttr() {
    
    // create array from selection
    string $sel[] = `ls -sl` ;
    // create array of selected attributes in the Channel Box
    string $selectedChannelBoxAttributes[] = `selectedChannelBoxAttributes` ;
    
    // for every item in selection
    for ($item in $sel) {
        // for each of it's selected attributes
    	for ($attribute in $selectedChannelBoxAttributes) {
            // zero the attribute value
            setAttr ($item + "." + $attribute) 0 ; 	        
        }
    }    
}